### ISSUE TITLE
token bug

### ISSUE THREAD

**Issue by Xiaocge** [easy-swoole/jwt#2]
我的环境是:
![image](https://user-images.githubusercontent.com/18593080/68472273-1670eb80-025b-11ea-9327-9ecc1a1707db.png)

decode token

![image](https://user-images.githubusercontent.com/18593080/68472326-343e5080-025b-11ea-9bdb-6cb033e6c6e9.png)

同一个token,出现 2个不同的结果.一个status为-1,一个为1.
`eyJhbGciOiJBRVMiLCJpc3MiOiJyb29tIiwiZXhwIjoxNTczMjE0MjIwLCJzdWIiOm51bGwsIm5iZiI6MTU3MzIxMDYyMCwiYXVkIjoxLCJpYXQiOjE1NzMyMTA2MjAsImp0aSI6IlRPSVVycHZmTm0iLCJzaWduYXR1cmUiOiJNUDlsVmZ6NEttTlNuZWJDa2RibnBhU1BPNjlCbGk2b01obERhcDltMGRZMEY4V0NXRGZWREVpOTh1UGJ1UEU2a2
o5L3N3enR2d2xyVmlETHFNWVZTVVRJRnRoT1JQeEMweHZRSTB2SytEVU9PcXovY3Fha2hYTnhPL0g1MGd4amZqOEFpaHZzYmhCVm1aTjNUcW1KRHZWNUJKMFVXMm1reUxtOVlDSzlkRlBrMk81Umk2UTlCVkM5eUIxQ0c4akwiLCJzdGF0dXMiOjEsImRhdGEiOnsiaWQiOjF9fQ%3D%3D`

![image](https://user-images.githubusercontent.com/18593080/68472544-b0389880-025b-11ea-8b62-d410daa2efd4.png)

**Comment by Xiaocge** [comment]
这种情况是偶然事件,不是每次都错.
我的代码是:   

```
private function validatorToken($token, $response)
	{
		$jwt = \EasySwoole\Jwt\Jwt::getInstance();
		try {
			/** @var \EasySwoole\Jwt\JwtObject $result */
			$result = $jwt->decode($token);
			var_dump($result, $token);
			switch ($result->getStatus()) {
				case  -2:
					$this->buildData($response, Status::CODE_UNAUTHORIZED, 'token过期');
//					echo 'token过期';
					break;
				case -1:
					$this->buildData($response, Status::CODE_UNAUTHORIZED, 'token无效');
//					echo 'token无效';
				case  1:
					return true;
//					echo '验证通过';
					break;
				case  2:
					$this->buildData($response, Status::CODE_UNAUTHORIZED, '验证失败');
//					echo '验证失败';
					break;
			}

			// 根据解密之后的结果完善业务逻辑
//			var_dump($result);
		} catch (\Exception $e) {
			$this->buildData($response, Status::CODE_UNAUTHORIZED, '非法错误');
		}
	}
```

**Comment by Xiaocge** [comment]
```
              $obj = \EasySwoole\Jwt\Jwt::getInstance()->algMethod('AES')->setSecretKey('room')->publish();
		$obj->setExp(time() + 3600);
		$obj->setAud($param['id']);
		$obj->setIss('room');
		$obj->setData($param);
                $token = $obj->__toString();
```
生成token以后,然后 结束掉  php easyswoole start          

```
$jwt = \EasySwoole\Jwt\Jwt::getInstance();
$result = $jwt->decode($token);
```
打印$result 就可复现出bug

**Comment by huizhang001** [comment]
感谢反馈！我看下

**Comment by huizhang001** [comment]
$jwt->setSecretKey('room')->decode($token); 你先这样用把

**Comment by baiachen** [comment]
这是因为你publish的时候setSecretKey，而decode的时候未setSecretKey，两次初始的SecretKey不一致造成的。
